name: Destroy Infrastructure

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  determine-env:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set-env.outputs.env_name }}
    steps:
      - id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "env_name=main" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            echo "env_name=qa" >> $GITHUB_OUTPUT
          else
            echo "env_name=dev" >> $GITHUB_OUTPUT
          fi

  terraform-destroy:
    name: 'Terraform Destroy'
    needs: determine-env
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-env.outputs.env_name }}
    defaults:
      run:
        working-directory: ./infra

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      # Backend configuration
      BACKEND_RG: "${{ needs.determine-env.outputs.env_name }}-bkd-alpinebot-2"
      BACKEND_SA: ${{ secrets.TF_BACKEND_STORAGE_ACCOUNT }}
      BACKEND_CONTAINER: "tfstate"
      BACKEND_KEY: "terraform.tfstate"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=$BACKEND_RG" \
            -backend-config="storage_account_name=$BACKEND_SA" \
            -backend-config="container_name=$BACKEND_CONTAINER" \
            -backend-config="key=$BACKEND_KEY"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false -var="environment=${{ needs.determine-env.outputs.env_name }}"
